package jason.infra.centralised;

import jason.jeditplugin.Config;
import jason.jeditplugin.MASLauncher;
import jason.mas2j.MAS2JProject;

import java.io.FileWriter;
import java.io.PrintWriter;

public class CentralisedMASLauncher extends MASLauncher {

	private boolean debug = false;
	
	public CentralisedMASLauncher(MAS2JProject project) {
		super(project);
	}
	
	public void stopMAS() {
		try {
			if (processOut != null) {
				processOut.write(1);//"quit"+System.getProperty("line.separator"));
			}
		} catch (Exception e) {
			System.err.println("Execution error: " + e);
			e.printStackTrace();
		}

		super.stopMAS();
	}

	/** return the operating system command that runs the MAS */
	public String getStartCommand() {
		return getRunScriptCommand(project.getSocName());
		/* the code below does not work! I didn't find a reason
		String sDebug = "";
		if (debug) {
			sDebug = " -debug";
		}
		String javacmd = "java";
		String javaHome = Config.get().getJavaHome();
		if (javaHome != null) {
			javacmd = javaHome+File.separator+"bin"+File.separator+"java";
		}
		return javacmd+" -classpath " + project.getProjectClassPath() + " "
				+ jason.infra.centralised.RunCentralisedMAS.class.getName() + " \""
				+ project.getProjectFile().getAbsolutePath() + "\" "+sDebug;
		*/
	}

	/** write the scripts necessary to run the project */	
	public void writeScripts(boolean debug) {
		this.debug = debug;
		try {
			String classPath = project.getProjectClassPath();
			String javaHome = Config.get().getJavaHome();
			
			PrintWriter out;
			
			// -- windows scripts
			if (System.getProperty("os.name").indexOf("indows") > 0) {
				out = new PrintWriter(new FileWriter(project.getDirectory() + project.getSocName() + ".bat"));
				out.println("@echo off\n");
				out.println("rem this file was generated by Jason\n");
				if (javaHome != null) {
					out.println("set PATH=\"" + javaHome + "bin\";%PATH%\n");
				}
				String sDebug = "";
				if (debug) {
					sDebug = " -debug";
				}
				out.println("java -classpath " + classPath + " "
						+ jason.infra.centralised.RunCentralisedMAS.class.getName() + " \""
						+ project.getProjectFile().getAbsolutePath() + "\" "+sDebug); //soc + ".xml\" ");
				out.close();

			} else {
				// ---- unix scripts
				// the script to run the MAS
				out = new PrintWriter(new FileWriter(project.getDirectory() + project.getSocName() + ".sh"));
				out.println("#!/bin/sh\n");
				out.println("# this file was generated by Jason\n");
				if (javaHome != null) {
					out.println("export PATH=\"" + javaHome + "bin\":$PATH\n");
				}
				String sDebug = "";
				if (debug) {
					sDebug = " -debug";
				}
				out.println("java -classpath " + classPath + " "
						+ jason.infra.centralised.RunCentralisedMAS.class.getName() + " \""
						+ project.getProjectFile().getAbsolutePath() + "\" "+sDebug); //soc + ".xml\"");
				out.close();
			}
		} catch (Exception e) {
			System.err.println("Could not write start script for project " + project.getSocName());
			e.printStackTrace();
		}
	}
}
