/* Generated By:JavaCC: Do not edit this line. as2jConstants.java */
package jason.asSyntax.parser;

public interface as2jConstants {

  int EOF = 0;
  int TK_TRUE = 7;
  int TK_FALSE = 8;
  int TK_NOT = 9;
  int TK_NEG = 10;
  int NUMBER = 11;
  int EXPONENT = 12;
  int STRING = 13;
  int ATOM = 14;
  int VAR = 15;
  int CHAR = 16;
  int LETTER = 17;
  int LC_LETTER = 18;
  int UP_LETTER = 19;
  int DIGIT = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"~\"",
    "<NUMBER>",
    "<EXPONENT>",
    "<STRING>",
    "<ATOM>",
    "<VAR>",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\".\"",
    "\"@\"",
    "\":\"",
    "\"<-\"",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"?\"",
    "\"&\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"\\\\==\"",
    "\"=\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"|\"",
  };

}
