/* Generated By:JavaCC: Do not edit this line. as2jConstants.java */
package jason.asSyntax.parser;

public interface as2jConstants {

  int EOF = 0;
  int TK_TRUE = 7;
  int TK_FALSE = 8;
  int TK_NOT = 9;
  int TK_NEG = 10;
  int TK_INTDIV = 11;
  int TK_LABEL_AT = 12;
  int NUMBER = 13;
  int EXPONENT = 14;
  int STRING = 15;
  int ATOM = 16;
  int VAR = 17;
  int UNNAMEDVAR = 18;
  int CHAR = 19;
  int LETTER = 20;
  int LC_LETTER = 21;
  int UP_LETTER = 22;
  int DIGIT = 23;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"~\"",
    "\"div\"",
    "\"@\"",
    "<NUMBER>",
    "<EXPONENT>",
    "<STRING>",
    "<ATOM>",
    "<VAR>",
    "\"_\"",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\".\"",
    "\":\"",
    "\"<-\"",
    "\"+\"",
    "\"-\"",
    "\"!\"",
    "\"?\"",
    "\"&\"",
    "\";\"",
    "\"!!\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"\\\\==\"",
    "\"=\"",
    "\"=..\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
  };

}
