/* Generated By:JavaCC: Do not edit this line. mas2jConstants.java */
package jason.mas2j.parser;

public interface mas2jConstants {

  int EOF = 0;
  int MAS = 7;
  int AGS = 8;
  int ENV = 9;
  int CONTROL = 10;
  int AT = 11;
  int ARCH = 12;
  int INFRA = 13;
  int INFRAV = 14;
  int ASOEE = 15;
  int ASOEEV = 16;
  int ASOIB = 17;
  int ASOIBV = 18;
  int ASONRC = 19;
  int ASOV = 20;
  int ASOSYNC = 21;
  int ASOBOOL = 22;
  int ASAGCLASS = 23;
  int ASAGARCHCLASS = 24;
  int NUMBER = 25;
  int STRING = 26;
  int ASID = 27;
  int CLASSID = 28;
  int PATH = 29;
  int DRIVER = 30;
  int LETTER = 31;
  int LC_LETTER = 32;
  int UP_LETTER = 33;
  int DIGIT = 34;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"MAS\"",
    "\"agents\"",
    "\"environment\"",
    "\"executionControl\"",
    "\"at\"",
    "\"architecture\"",
    "\"infrastructure\"",
    "<INFRAV>",
    "\"events\"",
    "<ASOEEV>",
    "\"intBels\"",
    "<ASOIBV>",
    "\"nrcbp\"",
    "\"verbose\"",
    "\"synchronised\"",
    "<ASOBOOL>",
    "\"agentClass\"",
    "\"agentArchClass\"",
    "<NUMBER>",
    "<STRING>",
    "<ASID>",
    "<CLASSID>",
    "<PATH>",
    "<DRIVER>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\":\"",
    "\"#\"",
    "\";\"",
    "\".\"",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"=\"",
  };

}
